Add ingest
nextstrain/measles pull request #10
Opened 2024-01-19 23:59 UTC by kimandrews

## Description of proposed changes

Update the measles workflow to follow the pathogen-repo-template.

2024-01-24 20:29 UTC, huddlej reviewed
This workflow ran for me without issue, @kimandrews. I added a couple of minor inline comments. Looking at these metadata and sequences for the first time, some thoughts I had were:

 1. We're throwing out a lot of data by filtering to 5000 bp sequences. It looks like the majority of sequences represent one or two genes (H and sometimes F, e.g., https://www.ncbi.nlm.nih.gov/nuccore/KJ183860.1). We should consider eventually building gene trees to use those smaller sequences.
 1. There are 6 samples with a host annotation that is not human (e.g., https://www.ncbi.nlm.nih.gov/nuccore/MG954083.1) and over 4000 without a host annotation at all. None of these samples have sequences that are long enough to get included in the current tree, but we should consider whether we want this workflow to produce human-specific measles trees or multi-host trees especially if we end up making gene trees. Since it's possible that the records without host annotations are not from human hosts, we would want a human-specific workflow to apply an additional host filter in the phylogenetic workflow.

A bigger issue I noticed when trying to use the outputs of this workflow for the phylogenetic workflow is that the use of the `strain` column as the metadata id column leads to duplicated records when running `augur filter` and causes the phylogenetic workflow to crash. I expect we'll need ingest to use the `accession` as the `strain` column, but that's probably something you've discussed with @j23414 and @joverlee521 already?

2024-01-24 22:30 UTC, joverlee521 requested changes
It's nice to see this come along @kimandrews ! I'm really glad the [zika examples](https://github.com/nextstrain/zika/pull/28) that @j23414 worked through was helpful! 

As we discussed in person, I think we can reduce confusion by removing the config parameters and rules that will not be used now. This includes the Entrez route for fetching sequences and the Nextclade related rules in `rules/nextclade.smk`.

2024-01-24 22:30 UTC, joverlee521 commented on ingest/config/defaults.yaml
> +  abbr_authors_field: "abbr_authors"
As we discussed earlier, this `abbr_authors` field is missing from the final outputs column in `metadata_columns` below.

2024-01-24 22:31 UTC, joverlee521 commented on ingest/vendored/.github/workflows/ci.yaml
Yeah, sadly there's no way to exclude specific directories/files from a subrepo.

2024-01-24 22:39 UTC, joverlee521 commented
>  the use of the strain column as the metadata id column leads to duplicated records when running augur filter and causes the phylogenetic workflow to crash. I expect we'll need ingest to use the accession as the strain column, but that's probably something you've discussed with @j23414 and @joverlee521 already?

Overall, we are going down the route of using `accession` as the `--metadata-id-column` for Augur commands instead of the default `strain` field. So this will require changes in the phylo workflow that should be included in future PRs.

2024-01-25 03:39 UTC, jameshadfield reviewed
Thanks Kim! Really useful for me to read through what a fresh ingest implementation using the new template repo looks like

2024-01-25 03:39 UTC, jameshadfield commented on ingest/config/defaults.yaml
> +# This configuration file should contain all required configuration parameters
[a general comment on the config, or perhaps the forthcoming tutorial, with the intention of discussion rather than specific changes]

Discussing this with Kim today most of the values were copied over from Zika. This includes the extracted NCBI fields (as thus, as discussed in another comment thread below, we're missing some important fields). It also includes the curate fields, which are necessarily data-dependent (e.g. expected date fields). Is the best-practice to fill in this config field-by-field after inspecting the raw NCBI data, or copy over from another repo and then asses the output?

2024-01-25 03:39 UTC, jameshadfield commented on ingest/bin/fix-measles-strain-names.py
> +        strain_name.replace(" ", "_")
The intention of these string replacements (copied from [zika](https://github.com/nextstrain/zika/blob/main/ingest/bin/fix-zika-strain-names.py#L43-L49)) seems to be to normalize the strain names for tree building etc. Since we are going to use accession as the ID for bioinformatics we can skip these character replacements.

2024-01-25 03:39 UTC, jameshadfield commented on ingest/rules/nextclade.smk
> +"""
Similar to [this previous comment](https://github.com/nextstrain/measles/pull/10/files#r1463747865) I think we should remove the nextclade-related rules and add them back in when we implement that functionality.

2024-01-25 03:39 UTC, jameshadfield commented on ingest/profiles/nextstrain_automation/defaults.yaml
(Very recently) I [think we've decided on how to rename the profiles directory](https://github.com/nextstrain/pathogen-repo-template/pull/27#issuecomment-1909151216)

2024-01-25 03:39 UTC, jameshadfield commented on ingest/profiles/nextstrain_automation/defaults.yaml
I think it'd be good practice to have this part of the workflow running as expected before we merge the PR.

The current measles data doesn't live in the canonical `s3://nextstrain-data/files/workflows/measles` location, so we could just use that, or to keep things clear you could use `s3://nextstrain-data/files/workflows/measles/test` or `s3://nextstrain-data/files/workflows/measles/pr10`. @joverlee521 what's best here?

2024-01-25 19:34 UTC, joverlee521 commented on ingest/README.md
> +nextstrain build .
Good point. `csvtk` and `tsv-utils` are getting used pretty regularly [across pathogen repos](https://github.com/search?q=org%3Anextstrain+AND+%28%22csvtk%22+OR+%22tsv-select%22%29&type=code) so definitely makes sense to add them to the ambient installation docs.

2024-01-25 19:39 UTC, joverlee521 commented on ingest/config/defaults.yaml
> +# This configuration file should contain all required configuration parameters
I had set up the template for the first route to force users to become familiar with the raw NCBI data and make conscious decisions to fill in the config. However, looking at this now, it might be too steep of a learning for new users.

Adding default values was also requested in https://github.com/nextstrain/pathogen-repo-template/issues/4 and Kim also provided feedback that it was easier to be able to run and assess the output before making changes. 
Seems like the template should just include the suggested default config params and users can then change them as needed.

2024-01-25 19:47 UTC, joverlee521 commented on ingest/profiles/nextstrain_automation/defaults.yaml
This PR was a first step in getting the core ingest workflow in place, we did not dig into the automation parts yet. 
We could just remove the `ingest/profiles` directory for now and add it as part of a later change.

2024-01-25 19:51 UTC, jameshadfield commented on ingest/profiles/nextstrain_automation/defaults.yaml
> We could just remove the ingest/profiles directory for now and add it as part of a later change.

Yup, that would be a fine outcome for this PR as well.

2024-01-25 19:53 UTC, jameshadfield commented on ingest/config/defaults.yaml
> +# This configuration file should contain all required configuration parameters
> Seems like the template should just include the suggested default config params and users can then change them as needed.

👍 I guess the tutorial is the best place to talk through _how_ one can asses the data to make the config specific to their data? Another option is to start with ~no curation and use that outcome to inform what curation steps to use.

2024-01-25 20:56 UTC, joverlee521 commented on ingest/bin/fix-measles-strain-names.py
> +        .replace(".", "_")
Ah, it might make more sense to change the order so that `fix-measles-strain-names` comes before `transform-strain-names` in the curate pipeline.

2024-01-25 23:43 UTC, joverlee521 commented on ingest/README.md
> +nextstrain build .
Adding in https://github.com/nextstrain/docs.nextstrain.org/pull/183. 
(Also threw `seqkit` in there since it's also another tool being used in workflows)

2024-01-30 01:27 UTC, kimandrews commented on ingest/rules/fetch_from_ncbi.smk
> +        """
Entrez rules and config parameters have been removed ([4e2ae25](https://github.com/nextstrain/measles/pull/10/commits/4e2ae25cfe0d4c74fa944de25664586bdbb1be73))

2024-01-30 01:34 UTC, kimandrews commented on ingest/bin/fix-measles-strain-names.py
As discussed, we decided not to manipulate strain names for measles, and so the script with this code has been removed.

2024-01-30 20:15 UTC, kimandrews commented on ingest/config/defaults.yaml
> +ncbi_datasets_fields:
@huddlej may have found `Virus Name` by running `dataformat tsv virus-genome` without the `--fields` option? `Virus Name` has now been added to the list of NCBI Datasets fields that are retrieved (https://github.com/nextstrain/measles/pull/10/commits/23622a803f60836bfd633274d1cfec895ac321b8)

2024-01-30 20:22 UTC, kimandrews commented on ingest/config/defaults.yaml
> +  abbr_authors_field: "abbr_authors"
Entrez rules and config parameters have been removed (https://github.com/nextstrain/measles/pull/10/commits/4e2ae25cfe0d4c74fa944de25664586bdbb1be73), and `abbr_authors` has been added to `metadata_columns` (https://github.com/nextstrain/measles/pull/10/commits/d7305f7e948696e8d7e618ef5d38eceb1ca3e9bd)

2024-01-30 20:25 UTC, kimandrews commented on ingest/README.md
> +# Ingest
Top-level `.gitignore` has been modified (https://github.com/nextstrain/measles/pull/10/commits/6763911a564cd84aaa93945eaec22b7413f78c6f)

2024-01-30 20:25 UTC, kimandrews commented on ingest/rules/curate.smk
> +    seuqences   = results/sequences.fasta
Fixed in [9dbf653](https://github.com/nextstrain/measles/pull/10/commits/9dbf65399e4c24e7a6bc54246ae4227877d3a1d4)

2024-01-30 20:35 UTC, kimandrews commented on ingest/bin/fix-measles-strain-names.py
> +        .replace(".", "_")
[As discussed](https://github.com/nextstrain/measles/pull/10#discussion_r1465795333), we decided not to manipulate strain names for measles, and so `ingest/bin/fix-measles-strain-names.py` has been removed.

2024-01-30 20:41 UTC, kimandrews commented on ingest/rules/nextclade.smk
> +"""
Nextclade-related rules have been removed ([43b36f9](https://github.com/nextstrain/measles/pull/10/commits/43b36f98d3bfca9e30e4304dc412d385ad2a40dd))

2024-01-31 18:13 UTC, kimandrews commented on ingest/bin/fix-measles-strain-names.py
Strain name manipulation has been removed, and empty strain names are no longer replaced ([56bfad6](https://github.com/nextstrain/measles/pull/10/commits/56bfad6649fa4d6f350565b63f7e23614363c8dc))

2024-01-31 22:34 UTC, joverlee521 requested changes
Thanks for working through the first round of feedback @kimandrews! 

I've left a couple more suggestions to remove more sections of the workflow that are not being used.

2024-01-31 22:34 UTC, joverlee521 commented on ingest/README.md
> +- [nextstrain_automation](profiles/nextstrain_automation/) - profile for the internal automated Nextstrain builds.
I would remove this section since we do not use any profiles now.

2024-01-31 22:34 UTC, joverlee521 commented on ingest/README.md
> +options to override these default values.
As part of changes in https://github.com/nextstrain/pathogen-repo-template/pull/27/commits/14e5dca9f8552c8427d7d4e360c964ca3ac1f8dd, the `config` directory is now expected to be named `defaults` and the default config is now expected to be `defaults/config.yaml`.

2024-01-31 22:34 UTC, joverlee521 commented on ingest/Snakefile
> +            """
I would remove this as well since the nextclade related rules have been removed. 

This will also require editing the [final rule in curate.smk](https://github.com/nextstrain/measles/blob/56bfad6649fa4d6f350565b63f7e23614363c8dc/ingest/rules/curate.smk#L123) to output `results/metadata.tsv` instead of `results/subset_metadata.tsv`.

2024-01-31 22:34 UTC, joverlee521 commented on ingest/rules/fetch_from_ncbi.smk
> +    - Requires a custom script to parse the necessary fields from the GenBank file
This section of the docstring can be removed since this workflow does not include Entrez rules anymore.

2024-02-01 00:32 UTC, kimandrews commented on ingest/bin/fix-measles-strain-names.py
> +        strain_name.replace(" ", "_")
[As discussed](https://github.com/nextstrain/measles/pull/10#discussion_r1465795333), we decided not to manipulate strain names for measles, and so ingest/bin/fix-measles-strain-names.py has been removed.

2024-02-01 00:33 UTC, kimandrews commented on ingest/profiles/nextstrain_automation/defaults.yaml
The ingest/profiles directory has been removed for now (https://github.com/nextstrain/measles/commit/601edee5f7bb558dfcf458a48a6a7c0eac53bc18)

2024-02-01 02:24 UTC, jameshadfield commented on ingest/bin/fix-measles-strain-names.py
Nice! 

For posterities sake, one thing I didn't quite realise is that those strain names above _were_ being "corrected", e.g.

```
original: up/2014-536-T
curated:  up/2014_536_T
```
which is another reason to skip name curation.

2024-02-01 02:31 UTC, jameshadfield commented on ingest/README.md
> +- metadata.tsv
It also includes `all_metadata.tsv`. 

In phylo workflows we have `{data,results,auspice}` and it's understood that the files in `results` can be numerous and change frequently with workflow updates. For ingest we only have `{data,results}`. My understanding is that more complex ingest workflows will populate `results` with many files. So maybe we could change the wording here to indicate that of the files in `results` these two are the ones that should be used for downstream analysis.

2024-02-01 02:43 UTC, jameshadfield commented on ingest/rules/curate.smk
> +rule curate:
_Consider the following an idea to implement later, it doesn't have to be part of this PR_

The virus name column contains information the phylo build will certainly want to show. It may even be the default colouring in auspice (or may be used as the basis for nextclade clade assignment which will then become the default colouring). The structure of values here is diverse, but the majority follow a straightforward pattern. Using `cat results/metadata.tsv | cut -f 3 | sort | uniq -c | sort -r`  the top 10 are:
```
6586 Measles morbillivirus
6557 Measles virus genotype D8
4883 Measles virus genotype B3
1546 Measles virus genotype D4
1341 Measles virus genotype H1
 668 Measles virus genotype D9
 158 Measles virus genotype H1a
 137 Measles virus genotype A
 131 Measles virus genotype D5
  72 Measles virus genotype B2
```

I don't think it'd be too hard to write a small script to extract as many genotypes as possible from this.

2024-02-01 03:10 UTC, jameshadfield commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
There are many more sample collection dates (or dates which we can effectively use as sample collection dates) beyond this field.

For strain names following [the WHO schema](https://www.cdc.gov/measles/lab-tools/genetic-analysis.html), the "XX.YY" corresponds to 

> Date of rash onset if known, otherwise date of specimen collection by epidemiological week (1-53) and year. 

So, e.g., Accession `JX187583`, which doesn't have a date in our workflow, has sample name `MVs/Parma.ITA/47.08` in [nuccore](https://www.ncbi.nlm.nih.gov/nuccore/JX187583) so it'd be `date=2008-11-XX`. 

Confusingly, looking at the raw NCBI dataset output that sample name does not appear¹, so there seems to be no way to extract it using the `datasets` command. I'm not an expert on the new datasets CLI (entrez, for all its messiness, is what I use), but I'd think it's worth working out what's going on here.


¹ Using the unzipped output from rule `fetch_ncbi_dataset_package`, then `grep 'JX187583' data/ncbi_dataset/ncbi_dataset/data/data_report.jsonl | gron`.

2024-02-02 00:15 UTC, joverlee521 commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
Thanks for pointing to the WHO schema for measles strain names! I've put in a [request to the NCBI datasets team](https://github.com/ncbi/datasets/issues/310) to add the `strain` field. We'll see if it's possible on their in end.

2024-02-02 00:31 UTC, joverlee521 commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
In the meantime, we have many records that _do_ have a strain name that are missing dates. 

So I'd think regardless of whether we use `datasets` or Entrez, it'd be worth writing a custom script to parse potential dates out of strain names.

2024-02-02 00:57 UTC, jameshadfield commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
Sounds good. Similar to [my comment above](https://github.com/nextstrain/measles/pull/10#discussion_r1473730032) I'd think it fine to defer for a later PR if @kimandrews wanted to merge this and get the phylo part working with this new ingest data. Your call.

2024-02-05 23:54 UTC, kimandrews commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
Thanks for the feedback and clarifications on how measles data is being reported in GenBank.

Of the current samples that meet our minimum length requirement (5000bp; n=937) and do not have dates listed (n=157), only 3 samples have strain names from which the sampling date could be inferred. 

I'm weighing the following options for moving forward:

1. Write custom code that will recover sampling dates for the 3 samples
2. Wait for NCBI Datasets to include the strain attribute, then write custom code that identifies which column the strain name is in (i.e. either the "strain" or "isolate" column) and subsequently uses strain name to infer sampling dates for samples with missing dates
3. Don't use NCBI Datasets; write custom code to parse the GenBank records
4. Only use samples that have sampling dates in the "date" column (don't try to infer missing dates from the strain name)
5. Other?

2024-02-06 00:07 UTC, jameshadfield commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
> only 3 samples have strain names from which the sampling date could be inferred

As in, only 3 have strain names as reported by the `datasets` program, or only 3 have strain names within entrez/nuccore?

2024-02-06 00:13 UTC, kimandrews commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
As reported by the `datasets` program. I haven't created any custom code for parsing GenBank records yet.

2024-02-06 00:21 UTC, jameshadfield commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
I'd recommend writing this up as an issue to tackle either later on or simultaneously with the phylo build. I think all 4 options could be comfortably considered out-of-scope for this PR. It seems that 'strain' will be parsed by NCBI sometime this year, and I don't it's unreasonable to wait for that, which gives a fair bit of time to think through the parsing approach and how it fits into the project. I don't know much about the temporal signal in measles phylogenetics, so I'd think to explore that as part of the phylo build in order to gauge how important filling in these missing data could be.

2024-02-06 00:35 UTC, joverlee521 commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
Number of samples with strain names might change when we change the minimum length filters for gene specific builds in #13. 

However, I also definitely support pushing this into a later issue.

2024-02-06 01:12 UTC, kimandrews commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
Yeah, without the minimum length filter, there are definitely more samples with strain names that could be used to recover empty dates. Seems worthwhile to eventually get this sorted out in a later PR.

2024-02-08 01:29 UTC, kimandrews commented on ingest/README.md
> +- [nextstrain_automation](profiles/nextstrain_automation/) - profile for the internal automated Nextstrain builds.
This change was made in [d68d3ef](https://github.com/nextstrain/measles/pull/10/commits/d68d3ef5bd23651e9eaf3b7426cbc1a7518dbc60)

2024-02-08 01:31 UTC, kimandrews commented on ingest/README.md
> +options to override these default values.
ingest/README.md was edited in [d68d3ef](https://github.com/nextstrain/measles/pull/10/commits/d68d3ef5bd23651e9eaf3b7426cbc1a7518dbc60), and the directory and file were renamed in [d7353b6](https://github.com/nextstrain/measles/pull/10/commits/d7353b6b5bf7c99c13eb35000938785ca1e7bca8)

2024-02-08 01:32 UTC, kimandrews commented on ingest/Snakefile
> +            """
These changes were made in [733694e](https://github.com/nextstrain/measles/pull/10/commits/733694e5cc57916ccd421fcf2539f0424111a800)

2024-02-08 01:34 UTC, kimandrews commented on ingest/rules/fetch_from_ncbi.smk
> +    - Requires a custom script to parse the necessary fields from the GenBank file
This change was made in [cc13eb6](https://github.com/nextstrain/measles/pull/10/commits/cc13eb6fd67fcec4a0a238dd174273c6b616fbe5)

2024-02-08 19:54 UTC, kimandrews commented on ingest/config/defaults.yaml
> +    isolate-collection-date: date
I created an [issue](https://github.com/nextstrain/measles/issues/14#issue-2123643372) about creating custom code to parse measles strain names

2024-02-11 18:34 UTC, j23414 commented on ingest/README.md
> +- metadata.tsv
Ah, the `all_metadata.tsv` looks like an intermediate data file, not the final result `metadata.tsv`. 

@kimandrews, you can change the path from `results/all_metadata.tsv` to `data/all_metadata.tsv` so there's less confusion on what the final output files should be (e.g. `results/sequences.fasta` and `results/metadata.tsv`.

https://github.com/nextstrain/measles/blob/90a70cd6ee151068368878cc0cbf0831302e5237/ingest/rules/curate.smk#L64

https://github.com/nextstrain/measles/blob/90a70cd6ee151068368878cc0cbf0831302e5237/ingest/rules/curate.smk#L119-L123

2024-02-11 18:59 UTC, j23414 commented on ingest/config/defaults.yaml
> +# This configuration file should contain all required configuration parameters
Good discussion! I went ahead and created an pathogen-repo-guide Issue to further discuss a ~no curation option: https://github.com/nextstrain/pathogen-repo-guide/issues/30

2024-02-11 20:21 UTC, j23414 commented on ingest/bin/fix-measles-strain-names.py
From [slack thread](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1707430446772039), deciding to `not replace empty strain names with accessions` may have downstream effects in the phylogenetic workflow (e.g. If we display strain name on tips, then Auspice will [generate a random string for the name](https://github.com/nextstrain/auspice/blob/cc6ef4e84da5b0df0cd8c8e4fa36b1db2e64fa2e/src/util/treeJsonProcessing.js#L23-L33) that is displayed in the tree...which is undesirable behaviour.

From @joverlee521 on the same thread:

> I think we can leave it as-is and just display the accession as the sequence name in the tree.
There's [WIP to allow Auspice to display arbitrary fields](https://github.com/nextstrain/auspice/pull/1668) as the name so we can then toggle between accession and strain name in the future.

@kimandrews, up-to-you if you want to revert https://github.com/nextstrain/measles/pull/10/commits/c9dfc647ccef1c61060d8e39199e1474a0dcd646 or leave it. We can also revisit this later, during your phylogenetic PR.

2024-02-12 20:57 UTC, joverlee521 approved these changes
I've left one final comment to address for the vendored subrepo, but the other changes look good to me.

2024-02-14 19:33 UTC, merged

2024-02-15 01:17 UTC, kimandrews commented on ingest/rules/curate.smk
> +rule curate:
I opened an issue for this [here](https://github.com/nextstrain/measles/issues/16#issue-2135458957)

2024-02-22 00:03 UTC, kimandrews commented on ingest/README.md
> +- metadata.tsv
Done in [f3fe0c1](https://github.com/nextstrain/measles/pull/17/commits/f3fe0c1950bf76c6233d7f5b014769ffd3b0912a)