Make nextclade tree
nextstrain/measles pull request #28
Opened 2024-04-30 21:33 UTC by kimandrews

## Description of proposed changes

This workflow creates a tree that can be used as part of a Nextclade dataset to assign genotypes to measles samples based on [criteria outlined by the WHO](https://www.who.int/publications/i/item/WER8709)

The tree created by this workflow includes N450 sequences for 28 reference strains defined by the WHO, along with other representative strains for each genotype that are obtained from the ingest output, using genotype assignments reported on NCBI. Genotypes are then assigned to each node with `augur clades`, using clade-defining mutations in `defaults/clades.tsv`.

Details regarding the workflow are described in a README.md

## Related issue(s)

## Checklist

- [ ] Checks pass

2024-05-01 23:31 UTC, trvrb commented
This is wonderful @kimandrews! Cleanly constructed in terms of the workflow and the result looks great in terms of consistency of MeV Genotypes and amount of data used. I think this will work well as a Nextclade reference tree.

2024-05-01 23:31 UTC, trvrb approved these changes

2024-05-01 23:36 UTC, joverlee521 approved these changes
Thanks for working through this Kim! The overall workflow looks good to me, I only left some minor comments. 

A couple high level thoughts (not blocking this PR): 
1. Will you be updating the workflow to create the full Nextclade dataset in the future? E.g. [mpox's nextclade workflow packages the whole dataset](https://github.com/nextstrain/mpox/blob/d7a55816b394db9acf0c8584c943d82a49f5137a/nextclade/Snakefile#L490-L516). 
2. Since there are a lot of shared files between phylogenetic and nextclade workflows, we could consider using a [shared directory](https://github.com/nextstrain/pathogen-repo-guide/tree/main/shared) to hold these files, so we don't need to duplicate the files across two directories.

2024-05-01 23:50 UTC, genehack reviewed
Extreme nitpick...

2024-05-01 23:50 UTC, genehack commented on nextclade/rules/export.smk
> +    """Exporting data files for for auspice"""
```suggestion
    """Exporting data files for auspice"""
```

2024-05-01 23:51 UTC, trvrb commented on nextclade/rules/annotate_phylogeny.smk
> +        aa_muts = "results/aa_muts.json",
I've historically preferred to only include nucleotide mutations in a `clades.tsv` specification as they are more exact and less prone to convergent evolution.

2024-05-01 23:54 UTC, trvrb commented
>Will you be updating the workflow to create the full Nextclade dataset in the future? E.g. [mpox's nextclade workflow packages the whole dataset](https://github.com/nextstrain/mpox/blob/d7a55816b394db9acf0c8584c943d82a49f5137a/nextclade/Snakefile#L490-L516).
Packaging up into a Nextclade dataset will be super useful. Would be nice to have this on the clades.nextstrain.org list.

>Since there are a lot of shared files between phylogenetic and nextclade workflows, we could consider using a [shared directory](https://github.com/nextstrain/pathogen-repo-guide/tree/main/shared) to hold these files, so we don't need to duplicate the files across two directories.
I personally don't mind the code duplication in this particular case. Easier for me to think about these as separate things. But it's not a strong preference.

2024-05-02 03:45 UTC, jameshadfield requested changes
Nice work @kim, only a few minor requests from me. I didn't run this locally, but tested out the tree that it produces by using the [use-nextclade-dataset branch](https://github.com/nextstrain/measles/tree/use-nextclade-dataset) which can also be loaded into [the nextclade web UI](https://clades.nextstrain.org/?dataset-url=https://github.com/nextstrain/measles/tree/use-nextclade-dataset/nextclade_dataset) and it's looking great.

2024-05-02 03:45 UTC, jameshadfield commented on nextclade/defaults/config.yaml
> +    colors: "defaults/colors.tsv"
The files `measles_reference_N450.gb`, `measles_reference_N450.fasta` are identical cf. the files in `phylogenetic/defaults/`. Jover recommended a shared directory but I think using `../phylogenetic/defaults/...` would be just fine.

2024-05-02 03:45 UTC, jameshadfield commented on nextclade/defaults/colors.tsv
> +region	Asia	#447CCD
Could you add a comment in this file and in phylogenetic/defaults/colors.tsv indicating that the region / genotype_ncbi fields are identical and that any changes to one should also be made to the other.

2024-05-02 03:45 UTC, jameshadfield commented on nextclade/rules/prepare_sequences.smk
> +            --query='genotype_ncbi!=""'
For the initial nextclade tree (i.e. we _haven't_ ever run nextclade to infer the genotypes) it's necessary to filter to those NCBI strains which have genotypes labelled so that we know which branches to use as clade-defining mutations. 

For future rebuilds of the nextclade tree where we will have nextclade inference already running in `ingest` this isn't strictly necessary, but I still think it'd be the correct way to do things.

2024-05-02 03:45 UTC, jameshadfield commented on nextclade/rules/annotate_phylogeny.smk
> +        aa_muts = "results/aa_muts.json",
(@kimandrews I know you have done a lot of work getting a tree you are happy with so if you choose to make changes here you should be able to re-run the rules from `clades` onwards and keep the tree the same. Make sure to create backups of the files just in case Snakemake decides to rebuild the tree!)

> I think that simplifies the workflow so that we don't have to run augur translate

We'd still want to run `augur translate` to have AA mutations on the tree within nextclade, right?

2024-05-07 21:35 UTC, kimandrews commented on nextclade/rules/prepare_sequences.smk
> +           -j 1 \
Implemented in [449aec0](https://github.com/nextstrain/measles/pull/28/commits/449aec00309d72020956292560315434b810f661)

2024-05-07 21:36 UTC, kimandrews commented on nextclade/rules/prepare_sequences.smk
> +        nextclade run \
Implemented in [449aec0](https://github.com/nextstrain/measles/pull/28/commits/449aec00309d72020956292560315434b810f661)

2024-05-07 21:37 UTC, kimandrews commented on nextclade/rules/export.smk
> +    """Exporting data files for for auspice"""
Fixed in [df7c7f0](https://github.com/nextstrain/measles/pull/28/commits/df7c7f044378b96e928da981754a7072c37ecd8b)

2024-05-07 21:40 UTC, kimandrews commented on nextclade/defaults/colors.tsv
> +region	Asia	#447CCD
Implemented in [df7c7f0](https://github.com/nextstrain/measles/pull/28/commits/df7c7f044378b96e928da981754a7072c37ecd8b)

2024-05-07 21:59 UTC, kimandrews commented on nextclade/rules/annotate_phylogeny.smk
> +        aa_muts = "results/aa_muts.json",
I removed amino acid mutations from clades.tsv in [df0ba96](https://github.com/nextstrain/measles/pull/28/commits/df0ba96f91581b1fb2629fc476a0ef3922f1f0dd) and confirmed that genotype assignments still look as expected on the tree when using this modified file. Many of the clade-defining amino acid mutations were already represented by the nucleotide-defining mutations, indicating the presence of redundancy.

2024-05-07 22:10 UTC, kimandrews commented on nextclade/defaults/config.yaml
> +    colors: "defaults/colors.tsv"
I appreciate hearing a variety of ideas on how to handle this. I don't feel strongly about any of the options, but I ended up deciding to keep the file structure the way it was to avoid potential confusion from having a shared folder, or having someone accidentally modify the reference files in the phylogenetic directory without realizing it would also affect the nextclade directory.

2024-05-08 16:54 UTC, joverlee521 approved these changes
Latest changes look good to me 👍

2024-05-09 20:17 UTC, trvrb commented
Looks like this may be ready to merge? @jameshadfield: Could you confirm?

2024-05-09 21:34 UTC, kimandrews commented
> Looks like this may be ready to merge? @jameshadfield: Could you confirm?

I talked with @jameshadfield yesterday and we are good to merge.

2024-05-09 21:35 UTC, merged