pull data from https instead of fauna
nextstrain/measles pull request #3
Opened 2022-03-25 21:38 UTC by j23414

### Description of proposed changes

To match the zika workflow, pull data from https instead of fauna (rethinkdb).

### Related issue(s)

Related to pull https://github.com/nextstrain/zika/pull/15

### Testing

To test the full pipeline:

```
cd measles
nextstrain build . 
```

To test the smaller test dataset

```
cd measles
mkdir -p data
cp -v example_data/* data/.
nextstrain build . 
```

2022-03-29 22:10 UTC, victorlin requested changes

2022-03-29 22:10 UTC, victorlin commented on .travis.yml
> +  - mamba install -c conda-forge -c bioconda augur auspice nextalign snakemake git --yes
With nextstrain/docs.nextstrain.org#102 the recommendation is to have just one `mamba create` vs. `mamba create` + `mamba install`:

```suggestion
  - mamba create -n nextstrain -c bioconda nextstrain-cli augur auspice nextalign snakemake git --yes
  - conda activate nextstrain
```

2022-03-30 16:10 UTC, victorlin approved these changes
Looks good! Would be good to clean up the git commit history with a `rebase`, or in the past I've used the **squash and merge** option on GitHub (but I don't think anyone else on the team prefers it). Let me know if you need help.

2022-04-01 17:25 UTC, j23414 commented
hmm, I might not have "merge" permissions for `nextstrain/measles`. Anyone else willing to merge?

2022-04-01 17:27 UTC, victorlin commented
@j23414 I just added @nextstrain/core as a writer to this repo so you should be able to do so now.

2022-04-01 17:34 UTC, merged

2022-04-01 17:40 UTC, tsibley requested changes

2022-04-01 18:19 UTC, j23414 commented on .travis.yml
>    - nextstrain update
From a "code smell" standpoint I agree with you @tsibley. The current expansion was a workaround until `pip3 install` was fixed for `.travis` testing. 

See https://github.com/nextstrain/zika/pull/14 for more details. Open other suggestions.

2022-04-01 19:47 UTC, victorlin commented on .travis.yml
>    - nextstrain update
Suggestions:

1. Move to GitHub Actions where we're using [`conda-incubator/setup-miniconda@v2`](https://github.com/marketplace/actions/setup-miniconda) in repos like [augur](https://github.com/nextstrain/augur/blob/d9aac582d27180c6c0f3078f0450243b454a2bb5/.github/workflows/ci.yaml#L33)
2. Only do `mamba install nextstrain-cli`
3. Make it more clear that Docker is being used. Maybe `nextstrain check-setup --set-default`? Unless there is a way to do something like `nextstrain --set-runtime docker`

2022-04-01 19:57 UTC, j23414 commented on .travis.yml
>    - nextstrain update
I like option 1, to move toward a consistent CI across repos :)

2022-04-01 20:02 UTC, tsibley commented on .travis.yml
>    - nextstrain update
Ah, I didn't see https://github.com/nextstrain/zika/pull/14. That's useful context.

I don't care too much about specifically conda/mamba vs. pip and Travis CI vs. GitHub Actions here, but good to be consistent when it makes sense (e.g. prefer GitHub Actions over Travis CI) and trim things down to minimal necessary steps.

Specifically here, I would wonder why did `pip install` start failing? Does it work now (i.e. was it transient)? It should work, and it's the simplest step (can be installed from latest PyPI release, doesn't have to be git and probably shouldn't be).

2022-04-01 20:05 UTC, tsibley commented on .travis.yml
>    - nextstrain update
> Make it more clear that Docker is being used

I think adding the `--docker` flag to the `nextstrain build` invocation would suffice ± a comment.

2022-04-01 20:46 UTC, j23414 commented on .travis.yml
>    - nextstrain update
Lol, I think we were both taxing .travis test at the same time. 

* https://app.travis-ci.com/github/nextstrain/zika/builds 

As long as it's working now, I'm happy