Use a config file to define hardcoded parameters
nextstrain/measles pull request #9
Opened 2024-01-12 00:44 UTC by kimandrews

## Description of proposed changes

Use a config file to define hardcoded parameters

## Checklist

- [ ] Checks pass

2024-01-12 01:16 UTC, j23414 approved these changes
[Automated checks passed](https://github.com/nextstrain/measles/actions/runs/7496369536/job/20408267478?pr=9) and local check passed:

```bash
git clone https://github.com/nextstrain/measles.git
cd measles
git checkout move-params-to-config
nextstrain build .
nextstrain view auspice
```

Changes look good to me!

2024-01-12 01:20 UTC, jameshadfield approved these changes

2024-01-12 01:49 UTC, joverlee521 approved these changes

2024-01-12 21:37 UTC, huddlej requested changes
This looks great, @kimandrews!

Following from [conversation on Slack in support of this idea](https://bedfordlab.slack.com/archives/C067ZLB3USH/p1705018979101929), can you also move the hardcoded file paths for configuration files to the config YAML file, too? I would follow the pattern we use for [the ncov workflow config files where we define a top-level "files" key](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#files) in the YAML such that most of the entries in the `files` rule map like this:

```yaml
files:
    exclude: "config/dropped_strains.txt"
    reference: "config/measles_reference.gb"
    colors: "config/colors.tsv"
    auspice_config: "config/auspice_config.json"
```

Since `input_fasta` doesn't get used anywhere and we instead download the data we need to start the workflow, we could just delete that line.

2024-01-16 23:18 UTC, huddlej approved these changes
Looks good to me! Thanks, @kimandrews!

2024-01-17 00:52 UTC, joverlee521 commented on config/config.yaml
> +    auspice_config: "config/auspice_config.json"
_non-blocking_

> I would follow the pattern we use for [the ncov workflow config files where we define a top-level "files" key](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#files) in the YAML such that most of the entries in the files rule map like this:

@huddlej, can you share some details on the reason ncov was originally set up like this? 
Specifically, why group under the top level `files` key instead of adding the files to specific param groups like so?
```yaml
filter:
    exclude: "config/dropped_strains.txt"
    ...
align:
    reference: "config/measles_reference.gb"
export:
    colors: "config/colors.tsv"
    auspice_config: "config/auspice_config.json"
```

2024-01-17 00:59 UTC, merged

2024-01-17 17:13 UTC, huddlej commented on config/config.yaml
> +    auspice_config: "config/auspice_config.json"
@joverlee521 That's a good question! The ncov pattern [came from the same impulse we felt in this PR to replace a `files` rule in the Snakefile with a YAML config](https://github.com/nextstrain/ncov/commit/f8c44774a0766e3ca1e5e5b2a6024f59c87afe7a#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bba). I think I wanted to emphasize the placement of the configuration details instead of suggesting their reorganization. (My memories from this time period are hazy though!)

The original reason for grouping all the config file paths into one section of the Snakefile must date back farther, but I suspect the main reason for that structure is that the same files can be needed by multiple rules. For example, we might need the `reference` file for `align`, `ancestral`, and `translate`. In the flu workflow, we need to reference the list of strains from `include` in both augur filter rules and [a later flag outliers rule](https://github.com/nextstrain/seasonal-flu/blob/c9473adf589cd211e9cbfa3f7678fd94a1769457/workflow/snakemake_rules/core.smk#L150). Even files that seem less ambiguously connected to a specific rule like the Auspice config JSON is to `export`, we also use the color scales from those JSONs in seasonal flu across multiple rules.

2024-01-17 20:39 UTC, joverlee521 commented on config/config.yaml
> +    auspice_config: "config/auspice_config.json"
I see. Thanks for the context @huddlej! 

Grouping files together makes sense if expected to be used multiple times. I also see the other side of it being confusing to need to edit configs for the `filter` rule under both `files` and `filter`. It's also not be immediately obvious looking at the config what rules use which files (unless you have [detailed docs like ncov](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#files)). 

Currently, I see configs using a mix of [top level `files` key](https://github.com/nextstrain/rsv/blob/0c053250e0f76e368aa3ede84c2d5e38fe32ebb8/config/configfile.yaml#L28-L30), [top level file name keys](https://github.com/nextstrain/mpox/blob/5d3a2675b5f3c2c142d8d65dd8937f093e9110be/phylogenetic/config/mpxv/config.yaml#L1-L9), and [rule specific file name keys](https://github.com/nextstrain/mpox/blob/5d3a2675b5f3c2c142d8d65dd8937f093e9110be/phylogenetic/config/mpxv/config.yaml#L20). We should come to some consensus on this schema as a group...I'll write up an issue on this in pathogen-repo-template.

2024-01-17 21:02 UTC, jameshadfield commented on config/config.yaml
> +    auspice_config: "config/auspice_config.json"
> It's also not be immediately obvious looking at the config what rules use which files (unless you have [detailed docs like ncov](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#files)).

I have spent plenty of time following the strings to work out which rules use which files (mainly in ncov), and often finding a bunch of files no longer used by any rule. Docs are great, but from experience they inevitably fall out of sync. I don't suppose you can write configs such as this can you?

```yaml
files:
  exclude:
     'config/exclude_accessions.txt'
filter:
  exclude: files['exclude']
```

P.S. Thanks @joverlee521 for the links to examples in your comment, it makes a big difference ✨

2024-01-17 21:54 UTC, joverlee521 commented on config/config.yaml
> +    auspice_config: "config/auspice_config.json"
We can continue discussion in https://github.com/nextstrain/pathogen-repo-template/issues/26